### ISSUE TITLE
Iban empty currency

### ISSUE THREAD

**Issue by faan11** [jbub/banking#11]
Hi,

We are using  this library to retrieve the currency from the iban.  We figure out that currency is empty after trying this iban: 
![image](https://github.com/jbub/banking/assets/763700/481259b1-ef12-49ba-9451-8a21ff90af48)
We are also trying different ibans but the currency is still empty. Are we missing something? We saw that you test only for United states and Mauritius.

Thank you in advance,

**Comment by jbub** [comment]
Hi, that is expected, only a few countries have currency included in the iban. https://en.wikipedia.org/wiki/International_Bank_Account_Number
