### ISSUE TITLE
Hard to use for redaction

### ISSUE THREAD

**Issue by dkegel-fastly** [jbub/banking#6]
The Validate() function doesn't return a length, so it is hard to use to redact the leading IBAN portion of a string.

**Comment by jbub** [comment]
Please can you tell me more about your use case ? Ideally with concrete example what you are trying to achieve :) Thank you!

**Comment by dkegel-fastly** [comment]
Sure.  I need to quickly find all IBAN codes in a string and replace them with a dummy string.

I will try to add better examples to the pull request.

**Comment by dkegel-fastly** [comment]
I made the test case a bit better, and updated ValidateWithLength() to pass.

This lets you iterate through a string, calling ValidateWithLength at that offset, to see if there is a valid IBAN number starting at each offset.

(It should probably take a flag to not check checksum, since in some redacting use cases, you want to redact anything that looks like an IBAN even if there is a typo in the middle.)

**Comment by jbub** [comment]
HI, i checked the PR, i dont really want to add `ValidateWithLength` to the API, it feels weird, maybe i am missing something but cant you just do this ? 

```go
ibn, err := iban.Parse(mystring)
if err != nil {
    // invalid iban
}
length := len(ibn.String())

// do your stuff here
```

**Comment by dkegel-fastly** [comment]
That was my first thought, and perhaps that is how Parse should work, but it does not currently work that way.

I will make that work and update the pull request...

**Comment by jbub** [comment]
What do you mean by should work ? I think you should do the tokenization on your side, split the string to words and then try to parse those words as iban.

**Comment by dkegel-fastly** [comment]
I'm replacing a regexp that fished IBAN-ish numbers out of bulk text, and my understanding is it needs to work even if the IBAN number is jammed up against another word without a separator.

I could maintain my own table mapping country codes to length of IBAN numbers, and use that to determine the ending point of a candidate number to pass to this library for validation... but was hoping to not have to do that.

**Comment by jbub** [comment]
Cant you use `country.GetBbanStructure()` directly then ?

**Comment by dkegel-fastly** [comment]
I guess so, sigh.

**Comment by jbub** [comment]
Guess we can close this one ?

**Comment by dkegel-fastly** [comment]
Closing.

**Comment by dkegel-fastly** [comment]
In case anyone else needs to redact IBAN numbers from bulk text, here's how I plan to extract length data for my state machine:
```
        fmt.Printf("// countryToIBANLen[s[0]-'A'][s[1]-A] gives total length of IBAN code starting with s[0..1]\n")
        fmt.Printf("var countryToIBANLen [26][26]uint8 = [26][26]uint8{\n")
        for i := 'A'; i <= 'Z'; i++ {
                fmt.Printf("\t{")
                for j := 'A'; j <= 'Z'; j++ {
                        bb, ok := country.GetBbanStructure(string([]rune{i, j}))
                        length := 0
                        if ok {
                                // IBAN is BBAN plus a four char prefix
                                length = 4 + bb.Length()
                        }
                        fmt.Printf("%d,", length)
                }
                fmt.Printf("},\n")
        }
        fmt.Printf("}\n")
```
This is fast, but has the disadvantage of needing to be updated when a new country is added to jbub.
